name: Execute Runner on Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_script:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python parsing script and capture output
        id: parse_output
        run: |
          echo -n "" > env_list.txt
          python -u src/parser.py > env_list.txt
          if [ ! -s env_list.txt ]; then
            echo "ERROR: Parser output file is empty after running parser.py"
            exit 1
          fi
          echo "Parser output:"
          cat env_list.txt

      - name: Run Python runner script for each environment
        continue-on-error: true
        run: |
          count=0
          while IFS=, read -r import_path env_name class_name; do
            echo "Read: $import_path, $env_name, $class_name"
            import_path=$(echo "$import_path" | xargs)
            env_name=$(echo "$env_name" | xargs)
            class_name=$(echo "$class_name" | xargs)
            if [ -z "$import_path" ] || [ -z "$env_name" ] || [ -z "$class_name" ]; then
              echo "Skipping invalid line: $import_path, $env_name, $class_name"
              continue
            fi
            echo "Running for: $import_path, $env_name, $class_name"
            python src/runner.py --import_path "$import_path" --cls_name "$class_name" --env_name "$env_name" --n_episodes 5 --max_steps_per_episode 100 || true
            ((count++))
          done < env_list.txt
          echo "Successfully processed $count environments."

      - name: Commit generated videos to current branch
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Junhaoo-Chen/VLA-RL-Tasks.git
          git add ./task_videos/
          git commit -m "Auto: Add generated files from CI run"
          git push origin HEAD:${{ github.ref_name }}